source 'https://rubygems.org'
gem 'foundation-rails' # Sorry, about that :-/
gem 'compass'
gem 'guard-compass'
gem 'guard-uglify'
gem 'guard-coffeescript'
gem 'guard-livereload'
gem 'guard-haml'
gem 'rack-livereload'
gem 'scss_lint'
gem 'jasmine'
gem 'foreman'
gem 'puma'
